name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci    
    - run: npm run lint
    - run: npm run build    
    - run: npm test
    - name: login test registry    
      run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873
    - run: npm version prerelease --no-git-tag-version
    - name: test publish publish
      run: npm publish --registry http://localhost:4873
    - name: test info check
      run: npm info @dianmora/contributors --json --registry http://localhost:4873      
